#!/usr/bin/env bash
# Assign variables for the private key and user
private_key=~/.ssh/school
user=ubuntu

# Connect to the server using ssh
ssh -i $private_key -o "StrictHostKeyChecking no" -o "User=$user" <server-address>
