#!/usr/bin/env bash
# Client configuration file
# file with user config
Host 98.98.98.98
    User Mkiige
    IdentityFile ~/.ssh/school
    PreferredAuthentications publickey
    PasswordAuthentication no
