#!/usr/bin/env bash
# Client configuration file
# file with user config
Host 3.235.75.142
    User Mkiige
    IdentityFile ~/.ssh/school
    PreferredAuthentications publickey
    PasswordAuthentication no
